import Head from "next/head";
// import Image from "next/image";
import { Inter } from "@next/font/google";
// import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

// import Image from "next/image";
// import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner/Banner";
import { bannerContent } from "@/data/bannerContent";
import ListSlider from "@/components/listSlider/ListSlider";
import {
  fetchSpaceXAPIDragon,
  fetchSpaceXAPILaunch,
  fetchSpaceXAPIMedia,
} from "@/lib/fetchSpaceXAPI";
import Dragon from "@/components/dragon/Dragon";
import { BannerData, dragonData, launchPad, mediaData } from "@/lib/types";
import SkeletonLoader from "@/components/skeleton/SkeletonLoader";

export async function getStaticProps() {
  const padData: launchPad[] = await fetchSpaceXAPILaunch();
  const dragonsData: dragonData[] = await fetchSpaceXAPIDragon();
  const mediaData: mediaData[] = await fetchSpaceXAPIMedia();

  fetchSpaceXAPIMedia();

  return {
    props: {
      padData,
      bannerContent,
      dragonsData,
      mediaData,
    },
    revalidate: 60,
  };
}

type HomeProps = {
  padData: launchPad[];
  bannerContent: BannerData;
  dragonsData: dragonData[];
  mediaData: mediaData[];
};

export default function Home(props: HomeProps) {
  const { padData, bannerContent, dragonsData, mediaData } = props;

  // console.log({ mediaData });
  return (
    <main>
      {/* <Head>
        <title>SpaceX | Daily</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      {/* <Navbar /> */}
      <Banner
        title={bannerContent.title}
        subTitle={bannerContent.subTitle}
        imgUrl={bannerContent.imgUrl}
      />
      <ListSlider title="Launch Pad" launchData={padData} display="launch" />

      <Dragon dragonsData={dragonsData} />

      <ListSlider title="Media" mediaData={mediaData} display="media" />
    </main>
  );
}
