import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Login = () => {
  return (
    <>
      <Head>
        <title>SpaceX | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          media="screen"
          href="https://fontlibrary.org//face/d-din"
          type="text/css"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="w-screen h-16  text-white text-xl fixed top-0 backdrop-blur-sm z-50 
        bg-gradient-to-b from-slate-900 opacity-90"
      >
        <Link href="/">
          <Image
            className="p-0 mr-1 absolute -top-16 left-4"
            src="/static/img/icon.svg"
            alt="library-icon"
            width={180}
            height={100}
          />
        </Link>
      </div>

      <main className="mx-auto  h-[500px] w-[100vw] flex items-center justify-center bg-login_feature bg-no-repeat backdrop-blur-sm opacity-90 object-cover">
        <form className="w-1/3 h-2/3 rounded-sm flex flex-col gap-y-1 items-center justify-evenly bg-slate-900/95 z-50">
          <h1 className="text-xl font-bold tracking-wider">
            Sign in using email
          </h1>
          <label className="block ">
            <span className="block text-2xl  tracking-wider font-bold text-white">
              Email
            </span>

            <input
              type="email"
              required
              className="text-black mt-2 h-10 p-1 text-bold rounded-md"
            />
          </label>

          <button className="bg-white font-bold text-black w-1/3 h-7 rounded-md">
            Sign In
          </button>
        </form>
      </main>
    </>
  );
};

export default Login;
