import Head from "next/head";
import Navbar from "../components/navbar/Navbar";
import { ReactNode } from "react";

type Props = {
  children?: ReactNode;
  // any props that come into the component
};

const Layout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>SpaceX | Daily</title>
        <meta
          name="Get Daily SpaceX data and livestreams"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          media="screen"
          href="https://fontlibrary.org//face/d-din"
          type="text/css"
        />
      </Head>
      <Navbar />
      {children}
    </>
  );
};

export default Layout;
